name: Read Env Var and Print

on:
  pull_request:
    branches:
      - main

jobs:
  print_env_var:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Print Environment Variable
        run: |
          echo "Environment Variable Value: ${{ vars.TEST }}"

